blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/AhmadAkd/onix-client/discussions
    about: Please ask and answer questions here.
  - name: GitHub Discussions
    url: https://github.com/AhmadAkd/onix-client/discussions
    about: Please ask and answer questions here.
