name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download sing-box.exe
      run: |
        Invoke-WebRequest -Uri "https://github.com/SagerNet/sing-box/releases/download/v1.12.8/sing-box-1.12.8-windows-amd64.zip" -OutFile "sing-box.zip"
        Expand-Archive -Path "sing-box.zip" -DestinationPath "."
        Move-Item "sing-box-1.12.8-windows-amd64/sing-box.exe" "sing-box.exe"

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-data "sing-box.exe;." main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: onix-windows-exe
        path: dist/main.exe