
name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build the application
      run: |
        # Create a version.txt file from the tag
        echo ${{ github.ref_name }} > version.txt
        # Run the build script
        cmd /c build.bat

    - name: Archive the build
      run: |
        Compress-Archive -Path dist\onix -DestinationPath onix-${{ github.ref_name }}-windows.zip

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: onix-${{ github.ref_name }}-windows.zip
        body: |
          Automated release for version ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
